{{- if .Values.minio.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lokistack.componentLabels" (dict "root" . "component" "minio") | nindent 4 }}
spec:
  replicas: {{ .Values.minio.replicas }}
  selector:
    matchLabels:
      {{- include "lokistack.componentSelectorLabels" (dict "root" . "component" "minio") | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "lokistack.componentSelectorLabels" (dict "root" . "component" "minio") | nindent 8 }}
    spec:
      {{- if .Values.minio.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minio-pvc
      {{- else }}
      volumes:
        - name: data
          emptyDir: {}
      {{- end }}
      containers:
        - name: minio
          image: {{ .Values.minio.image.repository }}:{{ .Values.minio.image.tag }}
          imagePullPolicy: {{ .Values.minio.image.pullPolicy }}
          args:
            - server
            - /data
            - --console-address
            - :{{ .Values.minio.service.uiPort }}
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: minio_root_user
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: minio_root_password
          ports:
            - containerPort: {{ .Values.minio.service.apiPort }}
              protocol: TCP
              name: api
            - containerPort: {{ .Values.minio.service.uiPort }}
              protocol: TCP
              name: ui
          volumeMounts:
            - name: data
              mountPath: /data
              {{- if .Values.minio.persistence.enabled }}
              subPath: minio
              {{- end }}
          resources:
            {{- toYaml .Values.minio.resources | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.minio.service.apiPort }}
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: {{ .Values.minio.service.apiPort }}
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
      restartPolicy: Always
{{- end }}
