{{- if .Values.minio.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lokistack.componentLabels" (dict "root" . "component" "minio") | nindent 4 }}
spec:
  type: {{ .Values.minio.service.type }}
  selector:
    {{- include "lokistack.componentSelectorLabels" (dict "root" . "component" "minio") | nindent 4 }}
  ports:
    - name: api
      protocol: TCP
      port: {{ .Values.minio.service.apiPort }}
      targetPort: {{ .Values.minio.service.apiPort }}
    - name: ui
      protocol: TCP
      port: {{ .Values.minio.service.uiPort }}
      targetPort: {{ .Values.minio.service.uiPort }}
{{- end }}
