{{- if .Values.minio.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lokistack.componentLabels" (dict "root" . "component" "minio") | nindent 4 }}
type: Opaque
stringData:
  minio_root_user: {{ .Values.minio.credentials.rootUser }}
  minio_root_password: {{ .Values.minio.credentials.rootPassword }}
{{- end }}
