---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.lokistack.storage.secret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lokistack.componentLabels" (dict "root" . "component" "loki") | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.minio.enabled }}
  endpoint: http://minio-service.{{ .Release.Namespace }}.svc:{{ .Values.minio.service.apiPort }}
  {{- else }}
  endpoint: {{ .Values.minio.endpoint }}
  {{- end }}
  region: {{ .Values.minio.region }}
  bucketnames: {{ .Values.minio.bucketName }}
  access_key_id: {{ .Values.minio.credentials.rootUser }}
  access_key_secret: {{ .Values.minio.credentials.rootPassword }}
