{{- if .Values.operators.loki.enabled }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: loki-operator
  namespace: {{ .Release.Namespace }}
spec:
  channel: {{ .Values.operators.loki.channel }}
  name: loki-operator
  source: {{ .Values.operators.loki.source }}
  sourceNamespace: {{ .Values.operators.loki.sourceNamespace }}
  installPlanApproval: {{ .Values.operators.loki.installPlanApproval }}
{{- end }}
