{{- if and .Values.operators.loki.enabled .Values.operators.operatorGroup.enabled }}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Release.Namespace }}-operators
  namespace: {{ .Release.Namespace }}
spec:
  targetNamespaces:
    - {{ .Release.Namespace }}
{{- end }}
