{{- if .Values.aapMock.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aap-mock
  labels:
    app: aap-mock
    {{- include "network.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aap-mock
  template:
    metadata:
      labels:
        app: aap-mock
    spec:
      containers:
        - name: aap-mock
          image: "{{ .Values.aapMock.image.repository }}:{{ .Values.aapMock.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: aap-mock
  labels:
    app: aap-mock
    {{- include "network.labels" . | nindent 4 }}
spec:
  selector:
    app: aap-mock
  ports:
    - port: 8080
      targetPort: 8080
{{- end }}
