{{- if .Values.secret.create }}
kind: Secret
apiVersion: v1
metadata:
  name: minio
  labels:
    {{- include "minio.labels" . | nindent 4 }}
data:
  user: {{ .Values.secret.user | b64enc | quote }}
  password: {{ .Values.secret.password | b64enc | quote }}
  host: {{ .Values.secret.host | b64enc | quote }}
  port: {{ .Values.secret.port | b64enc | quote }}
  access_key_id: {{ .Values.secret.user | b64enc | quote }}
  access_key_secret: {{ .Values.secret.password | b64enc | quote }}
  endpoint: {{ printf "http://%s:%s" .Values.secret.host .Values.secret.port | b64enc | quote }}
  bucketnames: {{ .Values.secret.lokistackBucket | b64enc | quote }}
  region: {{ .Values.secret.lokistackRegion | b64enc | quote }}
type: Opaque
{{- end }}
