{{- if .Values.grafana.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.grafana.rbac.serviceAccount.name }}
  namespace: {{ include "lokistack.namespace" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.grafana.rbac.lokiReader.serviceAccountName }}
  namespace: {{ include "lokistack.namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-loki-reader-application
  namespace: {{ include "lokistack.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-logging-application-reader
subjects:
  - kind: ServiceAccount
    name: {{ .Values.grafana.rbac.lokiReader.serviceAccountName }}
    namespace: {{ include "lokistack.namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-loki-reader-infrastructure
  namespace: {{ include "lokistack.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-logging-infrastructure-reader
subjects:
  - kind: ServiceAccount
    name: {{ .Values.grafana.rbac.lokiReader.serviceAccountName }}
    namespace: {{ include "lokistack.namespace" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-loki-token
  namespace: {{ include "lokistack.namespace" . }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.grafana.rbac.lokiReader.serviceAccountName }}
type: kubernetes.io/service-account-token
{{- end }}
