apiVersion: v2
name: hub
description: Helm chart for the hub component
type: application
version: 0.0.1
appVersion: 0.0.1

dependencies:
  - name: pgvector
    version: 0.5.5
    repository: https://rh-ai-quickstart.github.io/ai-architecture-charts
  - name: llama-stack
    version: 0.8.6
    repository: https://rh-ai-quickstart.github.io/ai-architecture-charts
  - name: mcp-servers
    version: 0.5.17
    repository: https://rh-ai-quickstart.github.io/ai-architecture-charts
    condition: mcp-servers.enabled
  - name: kafka
    version: 0.1.0
    repository: "file://../infra/kafka"
    condition: kafka.enabled
  - name: minio
    version: 0.5.5
    repository: "file://../infra/minio"
    condition: minio.enabled
  - name: lokistack
    version: 0.1.0
    repository: "file://../infra/lokistack/chart"
    condition: lokistack.enabled
