apiVersion: v2
name: hub
description: Helm chart for the hub component
type: application
version: 0.0.1
appVersion: 0.0.1

dependencies:
  # Remote charts
  - name: pgvector
    version: 0.5.5
    repository: https://rh-ai-quickstart.github.io/ai-architecture-charts
  - name: llama-stack
    version: 0.8.7
    repository: https://rh-ai-quickstart.github.io/ai-architecture-charts
  - name: mcp-servers
    version: 0.5.17
    repository: https://rh-ai-quickstart.github.io/ai-architecture-charts
    condition: mcp-servers.enabled
  # Local infrastructure subcharts
  - name: kafka
    version: 0.1.0
    repository: "file://charts/kafka"
    condition: kafka.enabled
  - name: minio
    version: 0.5.5
    repository: "file://charts/minio"
    condition: minio.enabled
  - name: milvus
    version: 0.1.0
    repository: "file://charts/milvus"
    condition: autorag.enabled
  - name: autorag
    version: 0.1.0
    repository: "file://charts/autorag"
    condition: autorag.enabled
  - name: lokistack
    version: 0.1.0
    repository: "file://charts/lokistack"
    condition: lokistack.enabled
