milvus:
  image:
    repository: milvusdb/milvus
    tag: v2.6.0
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: "2"
      memory: 4Gi
  storage:
    size: 20Gi

etcd:
  image:
    repository: quay.io/coreos/etcd
    tag: v3.5.5
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

secret:
  create: true
  rootPassword: "milvus-root-password"
