"""Shared ADNR topology helpers for CLUSTER_COUNT / spoke rendering."""

from __future__ import annotations


def spoke_count_for(cluster_count: int) -> int:
    if cluster_count < 1:
        raise ValueError("CLUSTER_COUNT must be >= 1")
    return 0 if cluster_count == 1 else cluster_count


def deployment_mode_for(cluster_count: int) -> str:
    return "single-cluster" if cluster_count == 1 else "hub-spoke"


def build_spokes(
    cluster_count: int,
    *,
    prefix: str = "edge-site",
    namespace: str = "dark-noc-edge",
) -> list[dict[str, str]]:
    count = spoke_count_for(cluster_count)
    return [
        {
            "name": f"{prefix}-{i:02d}",
            "siteId": f"edge-{i:02d}",
            "namespace": namespace,
        }
        for i in range(1, count + 1)
    ]


def render_values_yaml(
    cluster_count: int,
    *,
    prefix: str = "edge-site",
    namespace: str = "dark-noc-edge",
) -> str:
    mode = deployment_mode_for(cluster_count)
    spokes = build_spokes(cluster_count, prefix=prefix, namespace=namespace)
    lines = [
        "# Generated by scripts/topology/render-spokes.py. Do not edit by hand.",
        "topology:",
        f"  clusterCount: {cluster_count}",
        f"  deploymentMode: {mode}",
        f"  spokeCount: {len(spokes)}",
        f"  edgeNamespace: {namespace}",
        f"  spokeNamePrefix: {prefix}",
    ]
    if not spokes:
        lines.append("  spokes: []")
    else:
        lines.append("  spokes:")
        for spoke in spokes:
            lines.append(f"    - name: {spoke['name']}")
            lines.append(f"      siteId: {spoke['siteId']}")
            lines.append(f"      namespace: {spoke['namespace']}")
    lines.append("")
    return "\n".join(lines)
