"""Shared ADNR topology helpers for CLUSTER_COUNT / spoke rendering."""

from __future__ import annotations

import re

# Safe unquoted YAML scalars for spoke name prefix and namespace.
_SAFE_YAML_SCALAR = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*$")


def spoke_count_for(cluster_count: int) -> int:
    if cluster_count < 1:
        raise ValueError("CLUSTER_COUNT must be >= 1")
    return 0 if cluster_count == 1 else cluster_count


def deployment_mode_for(cluster_count: int) -> str:
    return "single-cluster" if cluster_count == 1 else "hub-spoke"


def _require_safe_scalar(name: str, value: str) -> str:
    if not value or not _SAFE_YAML_SCALAR.match(value):
        raise ValueError(
            f"{name} must be a non-empty DNS-like token "
            f"(letters, digits, ., _, -); got {value!r}"
        )
    return value


def build_spokes(
    cluster_count: int,
    *,
    prefix: str = "edge-site",
    namespace: str = "dark-noc-edge",
) -> list[dict[str, str]]:
    prefix = _require_safe_scalar("SPOKE_NAME_PREFIX", prefix)
    namespace = _require_safe_scalar("EDGE_NAMESPACE", namespace)
    count = spoke_count_for(cluster_count)
    return [
        {
            "name": f"{prefix}-{i:02d}",
            "siteId": f"edge-{i:02d}",
            "namespace": namespace,
        }
        for i in range(1, count + 1)
    ]


def render_mcp_openshift_volumes(
    spokes: list[dict[str, str]],
    *,
    prefix: str,
    service_account_name: str = "mcp-noc-openshift",
) -> list[str]:
    """Helm values overlay: mount per-spoke kubeconfig secrets for mcp-noc-openshift.

    Arrays replace (not merge) in Helm, so hub-spoke drops the single-cluster
    noc-openshift-edge-kubeconfig mount and mounts one secret per spoke instead.
    serviceAccountName must match multiClusterCreds.serviceAccountName (tokenFile auth).
    """
    sa = _require_safe_scalar("MCP_OPENSHIFT_SA", service_account_name)
    lines = [
        "mcp-servers:",
        "  mcp-servers:",
        "    noc-openshift:",
        f"      serviceAccountName: {sa}",
        "      env:",
        '        DEPLOYMENT_MODE: "hub-spoke"',
        '        KUBECONFIG_DIR: "/kubeconfigs"',
        f'        SPOKE_NAME_PREFIX: "{prefix}"',
        "      volumes:",
    ]
    for spoke in spokes:
        name = spoke["name"]
        lines.append(f"        - name: kc-{name}")
        lines.append("          secret:")
        lines.append(f"            secretName: noc-openshift-kubeconfig-{name}")
    lines.append("      volumeMounts:")
    for spoke in spokes:
        name = spoke["name"]
        lines.append(f"        - name: kc-{name}")
        lines.append(f"          mountPath: /kubeconfigs/{name}")
        lines.append("          readOnly: true")
    return lines


def render_values_yaml(
    cluster_count: int,
    *,
    prefix: str = "edge-site",
    namespace: str = "dark-noc-edge",
    mcp_service_account: str = "mcp-noc-openshift",
) -> str:
    # Hand-built YAML (stdlib only). Values are validated as safe scalars above.
    mode = deployment_mode_for(cluster_count)
    spokes = build_spokes(cluster_count, prefix=prefix, namespace=namespace)
    lines = [
        "# Generated by scripts/topology/render-spokes.py. Do not edit by hand.",
        "topology:",
        f"  clusterCount: {cluster_count}",
        f"  deploymentMode: {mode}",
        f"  spokeCount: {len(spokes)}",
        f"  edgeNamespace: {namespace}",
        f"  spokeNamePrefix: {prefix}",
    ]
    if not spokes:
        lines.append("  spokes: []")
    else:
        lines.append("  spokes:")
        for spoke in spokes:
            lines.append(f"    - name: {spoke['name']}")
            lines.append(f"      siteId: {spoke['siteId']}")
            lines.append(f"      namespace: {spoke['namespace']}")
        lines.append("")
        lines.append("multiClusterCreds:")
        lines.append(f"  serviceAccountName: {mcp_service_account}")
        lines.append("")
        lines.extend(
            render_mcp_openshift_volumes(
                spokes,
                prefix=prefix,
                service_account_name=mcp_service_account,
            )
        )
    lines.append("")
    return "\n".join(lines)
