"""Shared ADNR topology helpers for CLUSTER_COUNT / spoke rendering."""

from __future__ import annotations

import re

# Safe unquoted YAML scalars for spoke name prefix and namespace.
_SAFE_YAML_SCALAR = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*$")


def spoke_count_for(cluster_count: int) -> int:
    if cluster_count < 1:
        raise ValueError("CLUSTER_COUNT must be >= 1")
    return 0 if cluster_count == 1 else cluster_count


def deployment_mode_for(cluster_count: int) -> str:
    return "single-cluster" if cluster_count == 1 else "hub-spoke"


def _require_safe_scalar(name: str, value: str) -> str:
    if not value or not _SAFE_YAML_SCALAR.match(value):
        raise ValueError(
            f"{name} must be a non-empty DNS-like token "
            f"(letters, digits, ., _, -); got {value!r}"
        )
    return value


def build_spokes(
    cluster_count: int,
    *,
    prefix: str = "edge-site",
    namespace: str = "dark-noc-edge",
) -> list[dict[str, str]]:
    prefix = _require_safe_scalar("SPOKE_NAME_PREFIX", prefix)
    namespace = _require_safe_scalar("EDGE_NAMESPACE", namespace)
    count = spoke_count_for(cluster_count)
    return [
        {
            "name": f"{prefix}-{i:02d}",
            "siteId": f"edge-{i:02d}",
            "namespace": namespace,
        }
        for i in range(1, count + 1)
    ]


def render_values_yaml(
    cluster_count: int,
    *,
    prefix: str = "edge-site",
    namespace: str = "dark-noc-edge",
) -> str:
    # Hand-built YAML (stdlib only). Values are validated as safe scalars above.
    mode = deployment_mode_for(cluster_count)
    spokes = build_spokes(cluster_count, prefix=prefix, namespace=namespace)
    lines = [
        "# Generated by scripts/topology/render-spokes.py. Do not edit by hand.",
        "topology:",
        f"  clusterCount: {cluster_count}",
        f"  deploymentMode: {mode}",
        f"  spokeCount: {len(spokes)}",
        f"  edgeNamespace: {namespace}",
        f"  spokeNamePrefix: {prefix}",
    ]
    if not spokes:
        lines.append("  spokes: []")
    else:
        lines.append("  spokes:")
        for spoke in spokes:
            lines.append(f"    - name: {spoke['name']}")
            lines.append(f"      siteId: {spoke['siteId']}")
            lines.append(f"      namespace: {spoke['namespace']}")
    lines.append("")
    return "\n".join(lines)
