{{- if .Values.agentService.lightspeed.url }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-{{ .Release.Namespace }}-to-lightspeed
  namespace: {{ .Values.agentService.lightspeed.namespace | default "aap" }}
  labels:
    {{- include "hub.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: ansible-lightspeed-api
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Release.Namespace }}
      ports:
        - port: 8443
          protocol: TCP
{{- end }}
