{{- if and (not .Values.agentService.lightspeed.tokenSecretName) .Values.agentService.lightspeed.token }}
---
apiVersion: v1
kind: Secret
metadata:
  name: noc-lightspeed-secret
  labels:
    {{- include "hub.labels" . | nindent 4 }}
type: Opaque
data:
  LIGHTSPEED_TOKEN: {{ .Values.agentService.lightspeed.token | b64enc | quote }}
{{- end }}
