{{- if .Values.mcpSecrets.openshift.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: noc-openshift-edge-kubeconfig
  labels:
    {{- include "hub.labels" . | nindent 4 }}
type: Opaque
data:
  kubeconfig: {{ .Values.mcpSecrets.openshift.kubeconfig | b64enc | quote }}
{{- end }}
{{- if and .Values.mcpSecrets.aap.create (not .Values.mcpSecrets.aap.existingSecretName) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: noc-aap-secret
  labels:
    {{- include "hub.labels" . | nindent 4 }}
type: Opaque
data:
  AAP_TOKEN: {{ .Values.mcpSecrets.aap.token | default "" | b64enc | quote }}
{{- end }}
{{- if .Values.mcpSecrets.servicenow.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: noc-servicenow-secret
  labels:
    {{- include "hub.labels" . | nindent 4 }}
type: Opaque
data:
  SERVICENOW_USERNAME: {{ .Values.mcpSecrets.servicenow.username | b64enc | quote }}
  SERVICENOW_PASSWORD: {{ .Values.mcpSecrets.servicenow.password | b64enc | quote }}
{{- end }}
