{{- if and .Values.agentService.slack.botToken (not .Values.agentService.slack.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: noc-slack-secret
  labels:
    {{- include "hub.labels" . | nindent 4 }}
type: Opaque
data:
  SLACK_BOT_TOKEN: {{ .Values.agentService.slack.botToken | b64enc | quote }}
{{- end }}
