{{- if .Values.grafana.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: {{ include "lokistack.namespace" . }}
  labels:
    {{- include "lokistack.componentLabels" (dict "root" . "component" "grafana") | nindent 4 }}
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      {{- if .Values.grafana.datasources.loki.application.enabled }}
      - name: {{ .Values.grafana.datasources.loki.application.name }}
        type: loki
        access: proxy
        url: {{ include "lokistack.lokiGatewayUrl" . }}/application/
        isDefault: {{ .Values.grafana.datasources.loki.application.isDefault }}
        editable: false
        jsonData:
          tlsSkipVerify: {{ .Values.grafana.datasources.loki.application.tlsSkipVerify }}
          httpHeaderName1: 'Authorization'
        secureJsonData:
          httpHeaderValue1: 'Bearer $__file{/var/run/secrets/loki-token/token}'
      {{- end }}
      {{- if .Values.grafana.datasources.loki.infrastructure.enabled }}
      - name: {{ .Values.grafana.datasources.loki.infrastructure.name }}
        type: loki
        access: proxy
        url: {{ include "lokistack.lokiGatewayUrl" . }}/infrastructure/
        isDefault: {{ .Values.grafana.datasources.loki.infrastructure.isDefault }}
        editable: false
        jsonData:
          tlsSkipVerify: {{ .Values.grafana.datasources.loki.infrastructure.tlsSkipVerify }}
          httpHeaderName1: 'Authorization'
        secureJsonData:
          httpHeaderValue1: 'Bearer $__file{/var/run/secrets/loki-token/token}'
      {{- end }}
      {{- if .Values.grafana.datasources.loki.audit.enabled }}
      - name: {{ .Values.grafana.datasources.loki.audit.name }}
        type: loki
        access: proxy
        url: {{ include "lokistack.lokiGatewayUrl" . }}/audit/
        isDefault: {{ .Values.grafana.datasources.loki.audit.isDefault }}
        editable: false
        jsonData:
          tlsSkipVerify: {{ .Values.grafana.datasources.loki.audit.tlsSkipVerify }}
          httpHeaderName1: 'Authorization'
        secureJsonData:
          httpHeaderValue1: 'Bearer $__file{/var/run/secrets/loki-token/token}'
      {{- end }}
{{- end }}
