{{- if .Values.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "adnr-edge.namespace" . }}
  labels:
    {{- include "adnr-edge.labels" . | nindent 4 }}
    adnr.io/role: edge
{{- end }}
